name: Tag Version on Bump

on:
  push:
    paths:
      - pyproject.toml
      - .github/workflows/tag-version.yml # allow version tagging to proceed if this file needs to be fixed
    branches:
      - main  
jobs:
  tag_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for tags!

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep '^version' pyproject.toml | head -n 1 | sed 's/version = "\(.*\)"/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Tag commit if version bump and tag does not exist
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "v${{ steps.get_version.outputs.version }}"
          git push origin "v${{ steps.get_version.outputs.version }}"
